### ISSUE TITLE
Window?

### ISSUE THREAD

**Issue by slimshader** [fuqunaga/RapidGUI#13]
Hi, I went through all examples but I am still not sure how to just create a window with a Fields in it. I want the window to be just visible immediately and not launcher through WindowLauncher

**Comment by fuqunaga** [comment]
Try using RGUI.ResizableWindow() or [GUILayout.Window()](https://docs.unity3d.com/ScriptReference/GUILayout.Window.html).

```
screenRect = RGUI.ResizableWindow(windowID, screenRect, (_) =>
{
    value0 = RGUI.Field(value0, "value0");
    value1 = RGUI.Field(value1, "value1");

    GUI.DragWindow();
}, "Window");
```
